{% set version = "325" %}
{% set flatversion = version.replace(".", "") %}

package:
  name: libsvm
  version: {{ version }}

source:
  url: https://github.com/cjlin1/libsvm/archive/v{{ flatversion }}.tar.gz
  sha256: 1f587ec0df6fd422dfe50f942f8836ac179b0723b768fe9d2fabdfd1601a0963

  patches:
    - win32.patch  # [win32]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -e $PREFIX/include/svm.h                           # [unix]
    - test -e $PREFIX/lib/libsvm.so                           # [linux]
    - test -e $PREFIX/lib/libsvm.so.2                         # [linux]
    - test -e $PREFIX/lib/libsvm.dylib                        # [osx]
    - test -e $PREFIX/lib/libsvm.2.dylib                      # [osx]
    - svm-train | grep 'Usage'                                # [unix]
    - svm-scale | grep 'Usage'                                # [unix]
    - svm-predict | grep 'Usage'                              # [unix]
    - svm-train | findstr "Usage"                             # [win]
    - svm-scale | findstr "Usage"                             # [win]
    - svm-predict | findstr "Usage"                           # [win]
    - if not exist %PREFIX%\\Library\\lib\\libsvm.dll exit 1  # [win]

about:
  home: https://github.com/cjlin1/libsvm
  license: BSD-3-Clause
  license_file: COPYRIGHT
  summary: A simple, easy-to-use, and efficient software for SVM classification and regression.

extra:
  recipe-maintainers:
    - 183amir
    - bkpoon
    - patricksnape
