travis:
  secure:
    BINSTAR_TOKEN: mW24GVj7rem5uiX8K/WOuHsSySjVS4XgGIyZ+WyT6KmIaaj8KfTlB5SGcQ4bJhGQ6KFMCEvz4mm3jDmAEdxB70PevilXSVBUwY2qWdzIZhDHvZdWclA99tMAZZo8RgRkk7C3PzD/ApzRcMEMCAGsiSDULq4ipmOPA4Jw6uYd2zFqbt2FmLiMKCWJ/JojsVvkr/14GDZlL2pP4ub20fnId0hVl740/8idxLLwhyhCuYph+VkxExk40mL9o6oMS8bQeRiSHazJne23Vy0mtSw7ugfHFbsoJNvPQeGiskXZEmvIwC+46UCodL1qnAE4O2zBXC2UtdjqpaXBwAecSDWtKPETrfQwviVKv5mRSLMo+ktE+PlADwHmT3yZoiW/dh7XSRUeAS+ay57dFZlIFSEC5QoUl+dv1KdzU0sEL4OHFImzSoQ9Eh/M2eBYSlZNgkI2o+0maXeAjtz+E7TBWqJJydYJll4zQyF7A17pjKcxUTE7Ookkroh6QuUrXbol/ibKCnxDsTysNg3+GUS+4ZxLZUJbfVR5HNW+itEpj0qiPmIwN5NGQ0+ydjlCRyqcFM82yKSsXX1g4r2Bovv4b7EcxJFt1XtJcXW77tqzS7w+4k+XssTbHSrf8l1NMZFpgfSgc5itVkxoMfpTVsiOfrfTNaQQDZxz4Sh9hQBkJ/ENUZE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
