travis:
  secure:
    BINSTAR_TOKEN: l7sJLc3Cg/FQ3xW1cw1VI1Cjza0mQKArQ8RtDQQusBNyGPlEfEwcx4JImhYFuFiFJr94JJZxpcVW6rBmr67daSIhRa4DKIn4AMat2GkXFjzBNwF9g/KnwkMId3L2t1zSsIDmFmQOZbZYk4aIjz/vfrAsarCEr4m094dQGRbu6YeCZj58mrVCEgcmOmpiQCcU2kle/5GaCoQrHXsrs7cs/2niZfh9Q0TDBb0JE3rSrYu3dsF4yuxEnYexrh0E09aez7TlH+h9+itW7iLaUiP8BNlNJFcmhxdKtOESvq3RdivQe6cZrCOj8Gqw3WLpyDiDTADxTRKRqulz5gbm3BSZKWbMWPWEa6d3jTyZVi1O1z8wudynje+z3zkoBboMkWquXPgJHzeJPB2/iifVE+AwPpq9uQ8XOBhJ5CkOKL447r3u7eNJfO07yZI5N7W+E/jJ7tbY5IjZYua6xMAnh4st5MGs96JzfMjiQYovAj+NaCrKVyMCZHWCvrh3vky/hASEl6CpRMnXoBPyYG6mR1SwmS+296SKpuu33bEOy3bX4rAklsWH+OmadxwzMNpPQS7ZEF1SckCJi0QS+INluKvY2DDMw31Ij4kh+W4vZoGWDxdZp2IRR0hgXLiBAQXymhbtS9YUblOBVRx52N5cDuM5K6YLpY8b6e9RMCyWPiW1t6U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
